services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules

  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MARIADB_ROOT_PASSWORD: password
      MYSQL_DATABASE: bazar
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: