INSERT IGNORE INTO category (name) VALUES
('Motory'),
('Převodovky'),
('Budíky'),
('Elektronika'),
('Náhradní díly'),
('Pneumatiky'),
('Ráfky'),
('Brzdy'),
('Tlumiče'),
('Podvozky'),
('Karoserie'),
('Interiér'),
('Exteriér'),
('Osvětlení'),
('Zrcátka'),
('Skla'),
('Palubní desky'),
('Kola'),
('Motorové díly'),
('Příslušenství');